api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "price-guard"
type = "function"
uid = "53b88117-aab2-c181-c078-e569a2253014dce4b21a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
